/** @type {import("prettier").Config} */
export default {
  plugins: ['@ianvs/prettier-plugin-sort-imports'],
  arrowParens: 'always',
  jsxSingleQuote: true,
  printWidth: 120,
  semi: true,
  singleAttributePerLine: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
  importOrder: [
    '^react$',
    '',
    '<THIRD_PARTY_MODULES>',
    'interface',
    '(?=content|api)',
    'mock/',
    'lib/',
    'config/',
    'utils/',
    'helpers/',
    'guards/',
    'hooks/',
    'context/',
    'providers/',
    'layout/',
    'pages/',
    '(components/|./index)',
    '.svg',
    '^../(.*)$',
    '(?=./styles.module.scss)',
    '',
    '<TYPES>^(node:)',
    '<TYPES>',
    '<TYPES>^[.]',
  ],
  importOrderSeparation: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderTypeScriptVersion: '5.0.0',
};
